/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/ui/global/Avatar.vue')['default']
    Badge: typeof import('primevue/badge')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('./src/components/ui/global/Checkbox.vue')['default']
    Column: typeof import('primevue/column')['default']
    copy: typeof import('./src/components/ui/global/Input copy.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Input: typeof import('./src/components/ui/global/Input.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    MultiSelect: typeof import('./src/components/ui/global/MultiSelect.vue')['default']
    Panel: typeof import('primevue/panel')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    Password: typeof import('./src/components/ui/global/Password.vue')['default']
    ProfileBadge: typeof import('./src/components/ui/local/ProfileBadge.vue')['default']
    ProfileMenu: typeof import('./src/components/ui/local/ProfileMenu.vue')['default']
    Rating: typeof import('primevue/rating')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/ui/global/Select.vue')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    Tag: typeof import('primevue/tag')['default']
    Text: typeof import('./src/components/ui/global/Text.vue')['default']
    TreeTable: typeof import('primevue/treetable')['default']
  }
}
