export const DAY_ORDER_MAP: Record<string, number> = {
  monday: 0,
  tuesday: 1,
  wednesday: 2,
  thursday: 3,
  friday: 4,
  saturday: 5,
  sunday: 6,
  pazartesi: 0,
  salı: 1,
  çarşamba: 2,
  perşembe: 3,
  cuma: 4,
  cumartesi: 5,
  pazar: 6,
  montag: 0,
  dienstag: 1,
  mittwoch: 2,
  donnerstag: 3,
  freitag: 4,
  samstag: 5,
  sonntag: 6,
  lundi: 0,
  mardi: 1,
  mercredi: 2,
  jeudi: 3,
  vendredi: 4,
  samedi: 5,
  dimanche: 6,
  lunes: 0,
  martes: 1,
  miércoles: 2,
  jueves: 3,
  viernes: 4,
  sábado: 5,
  domingo: 6,
};

export const getDayIndex = (label: string): number => {
  const normalized = label.toLowerCase().trim();
  return DAY_ORDER_MAP[normalized] ?? -1;
};
